CREATE TABLE JEFE_COMITE ( 
    ID INT AUTO_INCREMENT PRIMARY KEY,
    RUT VARCHAR(10) NOT NULL UNIQUE,
    NOMBRE VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL UNIQUE
) ENGINE=InnoDB;

CREATE TABLE AUTOR (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    RUT VARCHAR(10) NOT NULL UNIQUE,
    NOMBRE VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL UNIQUE
) ENGINE=InnoDB;

CREATE TABLE TOPICO_ESPECIALIDAD (
    NOMBRE VARCHAR(50),
    CONSTRAINT PK_TOPICO_ESPECIALIDAD PRIMARY KEY (NOMBRE)
) ENGINE=InnoDB;

CREATE TABLE REVISOR (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    RUT VARCHAR(10) NOT NULL UNIQUE,
    NOMBRE VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    TOPICO_ESPECIALIDAD VARCHAR(50) NOT NULL,
    FOREIGN KEY (TOPICO_ESPECIALIDAD) REFERENCES TOPICO_ESPECIALIDAD(NOMBRE)
) ENGINE=InnoDB;

CREATE TABLE ARTICULO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(50) NOT NULL,
    AUTOR_CONTACTO INT NOT NULL,
    TOPICO_PRINCIPAL VARCHAR(50) NOT NULL,
    FECHA_ENVIO DATE NOT NULL,
    RESUMEN VARCHAR(150) NOT NULL,
    NUM_REVISORES INT DEFAULT 0,
    CONSTRAINT UQ_AUTOR_TITULO UNIQUE (TITULO, AUTOR_CONTACTO),
    CONSTRAINT FK_TOPICO_PRINCIPAL FOREIGN KEY (TOPICO_PRINCIPAL) REFERENCES TOPICO_ESPECIALIDAD(NOMBRE),
    CONSTRAINT FK_AUTOR_CONTACTO FOREIGN KEY (AUTOR_CONTACTO) REFERENCES AUTOR(ID)
) ENGINE=InnoDB;

CREATE TABLE AUTOR_PARTICIPANTE (
    ID_ARTICULO INT NOT NULL,
    ID_AUTOR INT NOT NULL,
    CONSTRAINT PK_AUTOR_PARTICIPANTE PRIMARY KEY (ID_ARTICULO, ID_AUTOR),
    CONSTRAINT FK_ID_ARTICULO FOREIGN KEY (ID_ARTICULO) REFERENCES ARTICULO(ID),
    CONSTRAINT FK_ID_AUTOR FOREIGN KEY (ID_AUTOR) REFERENCES AUTOR(ID)
) ENGINE=InnoDB;

CREATE TABLE TOPICOS_EXTRA (
    ID_ARTICULO INT NOT NULL,
    TOPICO_EXTRA VARCHAR(50) NOT NULL,
    CONSTRAINT PK_TOPICOS_EXTRA PRIMARY KEY (ID_ARTICULO, TOPICO_EXTRA),
    CONSTRAINT FK_ID_ARTICULO_TO_TOPICO FOREIGN KEY (ID_ARTICULO) REFERENCES ARTICULO(ID),
    CONSTRAINT FK_TOPICO_EXTRA FOREIGN KEY (TOPICO_EXTRA) REFERENCES TOPICO_ESPECIALIDAD(NOMBRE)
) ENGINE=InnoDB;

CREATE TABLE ESPECIALIDAD_AGREGADA (
    ID_REVISOR INT NOT NULL,
    ESPECIALIDAD_EXTRA VARCHAR(50) NOT NULL,
    CONSTRAINT PK_ESPECIALIDAD_AGREGADA PRIMARY KEY (ID_REVISOR, ESPECIALIDAD_EXTRA),
    CONSTRAINT FK_ID_REVISOR FOREIGN KEY (ID_REVISOR) REFERENCES REVISOR(ID),
    CONSTRAINT FK_ESPECIALIDAD_EXTRA FOREIGN KEY (ESPECIALIDAD_EXTRA) REFERENCES TOPICO_ESPECIALIDAD(NOMBRE)
) ENGINE=InnoDB;

CREATE TABLE ARTICULO_REVISOR (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_ARTICULO INT NOT NULL,
    ID_REVISOR INT NOT NULL,
    CONSTRAINT UQ_ARTICULO_REVISOR UNIQUE (ID_ARTICULO, ID_REVISOR),
    CONSTRAINT FK_ID_ARTICULO_TO_REVISOR FOREIGN KEY (ID_ARTICULO) REFERENCES ARTICULO(ID),
    CONSTRAINT FK_ID_REVISOR_TO_ARTICULO FOREIGN KEY (ID_REVISOR) REFERENCES REVISOR(ID)
) ENGINE=InnoDB;

CREATE TABLE REVISION (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ARTICULO_REVISOR_ID INT NOT NULL,
    puntuacion_global INT CHECK (puntuacion_global BETWEEN 1 AND 10),
    comentarios TEXT,
    originalidad INT CHECK (originalidad BETWEEN 1 AND 5),
    claridad INT CHECK (claridad BETWEEN 1 AND 5),
    relevancia INT CHECK (relevancia BETWEEN 1 AND 5),
    CONSTRAINT FK_ArticuloRevisor_Revision FOREIGN KEY (ARTICULO_REVISOR_ID) REFERENCES ARTICULO_REVISOR(ID)
) ENGINE=InnoDB;
